function cacaPalav(){

cacapala = new Array();
        cacapala = [
            [ 
                ['C', 'cfogo'],
                ['F', 'cnada'],
                ["D", 'cnada'],
                ["A", 'cnada'],
                ["J", 'cnada'],
                ["D", 'cnada'],
                ["T", 'cnada'],
                ["A", 'cnada'],
                ["M", 'cnada'],
                ["E", 'cnada'],
                ["C", 'cplanta'],
                ["S", 'cnada'],
                ["F", 'cagua'],
                ["Q", 'cnada'],
                ["S", 'cnada'],
                ["S", 'cagua'],
            ],       
            [ 
                ['E', 'cnada'],
                ['H', 'cfogo'],
                ["F", 'cnada'],
                ["A", 'cnada'],
                ["Ç", 'cnada'],
                ["A", 'cnada'],
                ["I", 'cnada'],
                ["G", 'cnada'],
                ["A", 'cnada'],
                ["G", 'cnada'],
                ["H", 'cplanta'],
                ["B", 'cnada'],
                ["R", 'cagua'],
                ["A", 'cnada'],
                ["D", 'cnada'],
                ["Q", 'cagua'],
            ],   
            [ 
                ['M', 'cnada'],
                ['A', 'cnada'],
                ["A", 'cfogo'],
                ["G", 'cnada'],
                ["A", 'cnada'],
                ["U", 'cnada'],
                ["U", 'cnada'],
                ["I", 'cnada'],
                ["R", 'cnada'],
                ["R", 'cnada'],
                ["I", 'cplanta'],
                ["S", 'cnada'],
                ["O", 'cagua'],
                ["Z", 'cnada'],
                ["Ç", 'cnada'],
                ["U", 'cagua'],
            ],       
            [ 
                ['Y', 'cnada'],
                ['M', 'cnada'],
                ["K", 'cnada'],
                ["R", 'cfogo'],
                ["X", 'cnada'],
                ["A", 'cnada'],
                ["N", 'cnada'],
                ["I", 'cnada'],
                ["A", 'cnada'],
                ["I", 'cnada'],
                ["C", 'cplanta'],
                ["A", 'cnada'],
                ["K", 'cagua'],
                ["L", 'cnada'],
                ["G", 'cnada'],
                ["I", 'cagua'],
            ],       
            [ 
                ['O', 'cnada'],
                ['Y', 'cnada'],
                ["I", 'cnada'],
                ["T", 'cnada'],
                ["M", 'cfogo'],
                ["S", 'cnada'],
                ["M", 'cnada'],
                ["T", 'cnada'],
                ["C", 'cnada'],
                ["M", 'cnada'],
                ["O", 'cplanta'],
                ["F", 'cnada'],
                ["I", 'cagua'],
                ["J", 'cnada'],
                ["M", 'cnada'],
                ["R", 'cagua'],
            ],   
            [ 
                ['G', 'cnada'],
                ['A', 'cnada'],
                ["U", 'cnada'],
                ["A", 'cnada'],
                ["A", 'cnada'],
                ["A", 'cfogo'],
                ["A", 'cnada'],
                ["L", 'cnada'],
                ["U", 'cnada'],
                ["A", 'cnada'],
                ["R", 'cplanta'],
                ["T", 'cnada'],
                ["E", 'cagua'],
                ["F", 'cnada'],
                ["K", 'cnada'],
                ["T", 'cagua'],
            ],       
            [ 
                ['C', 'cfogo'],
                ['Y', 'cfogo'],
                ["N", 'cfogo'],
                ["D", 'cfogo'],
                ["A", 'cfogo'],
                ["Q", 'cfogo'],
                ["U", 'cfogo'],
                ["I", 'cfogo'],
                ["L", 'cfogo'],
                ["S", 'cnada'],
                ["I", 'cplanta'],
                ["D", 'cnada'],
                ["R", 'cnada'],
                ["I", 'cnada'],
                ["Ç", 'cnada'],
                ["L", 'cagua'],
            ],               
            [ 
                ['E', 'cnada'],
                ['A', 'cnada'],
                ["T", 'cnada'],
                ["R", 'cnada'],
                ["U", 'cnada'],
                ["P", 'cnada'],
                ["A", 'cnada'],
                ["D", 'cfogo'],
                ["A", 'cnada'],
                ["I", 'cnada'],
                ["T", 'cplanta'],
                ["V", 'cnada'],
                ["Y", 'cnada'],
                ["U", 'cnada'],
                ["I", 'cnada'],
                ["E", 'cagua'],
            ],    
            [ 
                ['D', 'cnada'],
                ['J', 'cnada'],
                ["H", 'cnada'],
                ["W", 'cnada'],
                ["J", 'cnada'],
                ["W", 'cnada'],
                ["O", 'cnada'],
                ["Ç", 'cnada'],
                ["E", 'cfogo'],
                ["U", 'cnada'],
                ["A", 'cplanta'],
                ["O", 'cnada'],
                ["Ç", 'cnada'],
                ["E", 'cnada'],
                ["Q", 'cnada'],
                ["X", 'cnada'],
            ],       
            [ 
                ['C', 'cplanta'],
                ['H', 'cplanta'],
                ["E", 'cplanta'],
                ["S", 'cplanta'],
                ["P", 'cplanta'],
                ["I", 'cplanta'],
                ["N", 'cplanta'],
                ["I", 'cnada'],
                ["R", 'cnada'],
                ["R", 'cfogo'],
                ["S", 'cnada'],
                ["G", 'cnada'],
                ["V", 'cnada'],
                ["B", 'cnada'],
                ["C", 'cnada'],
                ["H", 'cnada'],
            ],  
            [ 
                ['W', 'cnada'],
                ['J', 'cnada'],
                ["J", 'cnada'],
                ["T", 'cnada'],
                ["P", 'cnada'],
                ["F", 'cnada'],
                ["M", 'cnada'],
                ["Z", 'cnada'],
                ["C", 'cnada'],
                ["Ç", 'cnada'],
                ["S", 'cnada'],
                ["W", 'cnada'],
                ["T", 'cnada'],
                ["K", 'cnada'],
                ["D", 'cnada'],
                ["M", 'cnada'],
            ], 
            [ 
                ['Q', 'cnada'],
                ['S', 'cnada'],
                ["D", 'cnada'],
                ["G", 'cnada'],
                ["X", 'cnada'],
                ["Z", 'cnada'],
                ["H", 'cnada'],
                ["X", 'cnada'],
                ["K", 'cagua'],
                ["A", 'cagua'],
                ["L", 'cagua'],
                ["W", 'cagua'],
                ["P", 'cagua'],
                ["L", 'cagua'],
                ["Ç", 'cagua'],
                ["C", 'cagua'],

            ],
            [ 
                ['J', 'cnada'],
                ['D', 'cnada'],
                ["Q", 'cnada'],
                ["N", 'cnada'],
                ["Ç", 'cnada'],
                ["F", 'cnada'],
                ["G", 'cnada'],
                ["P", 'cnada'],
                ["Q", 'cnada'],
                ["S", 'cnada'],
                ["R", 'cnada'],
                ["T", 'cnada'],
                ["G", 'cnada'],
                ["Z", 'cnada'],
                ["Z", 'cnada'],
                ["T", 'cnada'],

            ],
            [ 
                ['F', 'cfogo'],
                ['E', 'cfogo'],
                ["N", 'cfogo'],
                ["N", 'cfogo'],
                ["E", 'cfogo'],
                ["K", 'cfogo'],
                ["I", 'cfogo'],
                ["N", 'cfogo'],
                ["R", 'cnada'],
                ["A", 'cnada'],
                ["D", 'cnada'],
                ["S", 'cnada'],
                ["A", 'cnada'],
                ["V", 'cnada'],
                ["Z", 'cnada'],
                ["D", 'cnada'],

            ],
            [ 
                ['R', 'cnada'],
                ['A', 'cnada'],
                ["I", 'cnada'],
                ["D", 'cnada'],
                ["Z", 'cnada'],
                ["F", 'cnada'],
                ["C", 'cnada'],
                ["Z", 'cnada'],
                ["S", 'cnada'],
                ["F", 'cnada'],
                ["C", 'cnada'],
                ["N", 'cnada'],
                ["K", 'cnada'],
                ["V", 'cnada'],
                ["X", 'cnada'],
                ["Z", 'cnada'],

            ],
            [ 
                ['B', 'cplanta'],
                ['U', 'cplanta'],
                ["L", 'cplanta'],
                ["B", 'cplanta'],
                ["A", 'cplanta'],
                ["S", 'cplanta'],
                ["S", 'cplanta'],
                ["A", 'cplanta'],
                ["U", 'cplanta'],
                ["R", 'cplanta'],
                ["O", 'cplanta'],
                ["L", 'cnada'],
                ["F", 'cnada'],
                ["A", 'cnada'],
                ["C", 'cnada'],
                ["N", 'cnada'],

            ],       

        ];  
        for(linha=0;linha<16;linha++) {
            document.write("<tr>");
                for(coluna=0;coluna<16;coluna++) {
                    document.write("<td class='" + cacapala[linha][coluna][1] + "'>" + cacapala[linha][coluna][0] + "</td>");
                }
            document.write('</tr>');
        }
    }